# Generated by Django 3.0.1 on 2020-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adduser',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
